services:
  backend:
    user: "root"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media