events {}

http {
    upstream backend {
        server backend:8000;
    }

    server {
        listen 80;
        server_name www.kamykowe-rekodzielo.pl;
        return 301 http://kamykowe-rekodzielo.pl$request_uri;
    }

    server {
        listen 80;
        server_name kamykowe-rekodzielo.pl;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        return 301 https://kamykowe-rekodzielo.pl$request_uri;
    }

    server {
        listen 443 ssl;
        server_name www.kamykowe-rekodzielo.pl;

        ssl_certificate /etc/letsencrypt/live/kamykowe-rekodzielo.pl/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/kamykowe-rekodzielo.pl/privkey.pem;

        return 301 https://kamykowe-rekodzielo.pl$request_uri;
    }

    server {
        listen 443 ssl;
        server_name kamykowe-rekodzielo.pl;

        ssl_certificate /etc/letsencrypt/live/kamykowe-rekodzielo.pl/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/kamykowe-rekodzielo.pl/privkey.pem;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}