# Generated by Django 5.2.8 on 2026-01-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_size_product_description_product_product_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_code',
            new_name='code',
        ),
    ]
