# Generated by Django 5.2.8 on 2025-11-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_stone_remove_product_image_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='upload',
        ),
    ]
